# Generated by Django 4.1.5 on 2023-01-22 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('tg_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('prop_address', models.CharField(max_length=300)),
                ('passport', models.CharField(max_length=10)),
                ('mark', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('product_count', models.IntegerField(max_length=10)),
                ('price', models.CharField(max_length=20)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.client')),
            ],
        ),
    ]
