# Generated by Django 4.1.5 on 2023-01-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
