# Generated by Django 4.1.5 on 2023-01-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_date']},
        ),
        migrations.AddField(
            model_name='client',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
