# Generated by Django 4.1.5 on 2023-02-01 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_options_client_update_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['update_date']},
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('mark_id', models.AutoField(primary_key=True, serialize=False)),
                ('mark', models.CharField(blank=True, max_length=150, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='app.client')),
            ],
        ),
    ]
