# Generated by Django 4.1.5 on 2023-02-01 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_client_options_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='app.client'),
        ),
    ]
